# .github/workflows/rush.yml
name: Rush CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Rush Install
        uses: advancedcsg-open/actions-rush@v1.4.5
        with:
          build: true
          run: rush version --bump
